import { Topic, PodcastConfig } from "../types";

/**
 * Pulse Studio - Application Constants
 */

export const DEFAULT_TOPICS: Topic[] = [
  { id: '1', emoji: '🤖', text: 'AI technologies and apps — latest launches and breakthroughs', enabled: true, percentage: 20 },
  { id: '2', emoji: '₿', text: 'Cryptocurrency — top predictions, trends and news', enabled: true, percentage: 15 },
  { id: '3', emoji: '📈', text: 'Share market news, tips and investment suggestions', enabled: true, percentage: 20 },
  { id: '4', emoji: '💻', text: 'Tech industry news and major product updates', enabled: true, percentage: 15 },
  { id: '5', emoji: '🏢', text: 'Company mergers, acquisitions and big business deals', enabled: true, percentage: 10 },
  { id: '6', emoji: '🚀', text: 'High-potential emerging companies to watch', enabled: true, percentage: 10 },
  { id: '7', emoji: '🌍', text: 'Global macro news: crude oil, gold, war, geopolitics affecting markets', enabled: true, percentage: 10 },
];

export const VOICES = ['Zephyr', 'Kore', 'Puck', 'Charon', 'Fenrir'];

export const APP_NAME = "Pulse Studio";
export const APP_DESCRIPTION = "Your personal AI-powered podcast studio.";

export const DEFAULT_CONFIG: PodcastConfig = {
  duration: 10,
  numHosts: 2,
  hosts: [
    { name: 'Arjun', geminiVoice: 'Zephyr', elevenLabsVoice: '', murfVoice: '', audixaVoice: '' },
    { name: 'Priya', geminiVoice: 'Kore', elevenLabsVoice: '', murfVoice: '', audixaVoice: '' },
    { name: 'Sameer', geminiVoice: 'Puck', elevenLabsVoice: '', murfVoice: '', audixaVoice: '' }
  ],
  podcastName: 'The Daily Brief India',
  newsFetcherProvider: 'groq',
  scriptWriterProvider: 'groq',
  voiceGeneratorProvider: 'gemini-tts',
  groqKey: '',
  geminiKey: '',
  claudeKey: '',
  openaiKey: '',
  elevenLabsKey: '',
  murfKey: '',
  audixaKey: '',
  customProviders: [],
  autoGenerate: true,
  pwaEnabled: false,
  pwaTime: '07:00',
  pwaDays: [1, 2, 3, 4, 5],
  pwaNotifications: true,
  automationMethods: ['pwa', 'macrodroid'],
  userName: 'Nithin',
  pretext: 'Hey [name]. The podcast topics are as per your suggestions.',
  autoGenerateDuration: 10,
  autoDownload: false,
  whatsappEnabled: false,
  whatsappNumber: '',
  whatsappAutoSend: false,
  whatsappMethod: 'link',
  whatsappWebhookUrl: '',
  whatsappApiKey: ''
};
