export interface Host {
  name: string;
  geminiVoice: string;
  elevenLabsVoice: string;
  murfVoice: string;
  audixaVoice: string;
}

export interface Topic {
  id: string;
  emoji: string;
  text: string;
  enabled: boolean;
  percentage: number;
}

export interface CustomProvider {
  id: string;
  name: string;
  type: 'llm' | 'tts';
  url: string;
  authHeader: string;
  authPrefix: string;
  apiKey: string;
  payloadTemplate: string;
  responsePath: string;
}

export type LLMProvider = 'groq' | 'gemini-flash' | 'gemini-pro' | 'claude' | 'openai' | 'custom';
export type TTSProvider = 'gemini-tts' | 'elevenlabs' | 'murf' | 'audixa' | 'custom';

export interface PodcastConfig {
  duration: number;
  numHosts: number;
  hosts: Host[];
  podcastName: string;
  newsFetcherProvider: LLMProvider;
  scriptWriterProvider: LLMProvider;
  voiceGeneratorProvider: TTSProvider;
  groqKey: string;
  geminiKey: string;
  claudeKey: string;
  openaiKey: string;
  elevenLabsKey: string;
  murfKey: string;
  audixaKey: string;
  customProviders: CustomProvider[];
  autoGenerate: boolean;
  pwaEnabled: boolean;
  pwaTime: string;
  pwaDays: number[];
  pwaNotifications: boolean;
  automationMethods: string[];
  userName: string;
  pretext: string;
  autoGenerateDuration: number;
  autoDownload: boolean;
  whatsappEnabled: boolean;
  whatsappNumber: string;
  whatsappAutoSend: boolean;
  whatsappMethod: 'link' | 'webhook' | 'callmebot';
  whatsappWebhookUrl: string;
  whatsappApiKey: string;
  lastGeneratedDate?: string;
}
