import React from 'react';
import { 
  Zap, 
  Link, 
  Smartphone, 
  Clock, 
  Bell, 
  Download,
  Copy 
} from 'lucide-react';
import { PodcastConfig } from '../types';

interface AutomatePanelProps {
  config: PodcastConfig;
  setConfig: (c: PodcastConfig) => void;
  requestNotificationPermission: () => void;
  downloadAutomationHtml: () => void;
  notify: (msg: string, type: 'success' | 'error' | 'info') => void;
}

export const AutomatePanel: React.FC<AutomatePanelProps> = ({
  config,
  setConfig,
  requestNotificationPermission,
  downloadAutomationHtml,
  notify
}) => {
  return (
    <div className="panel show">
      <div className="app-card" style={{ marginBottom: '16px' }}>
        <div className="app-name">Pulse Automator</div>
        <div className="app-desc">Run your podcast studio automatically at your scheduled time using simple mobile apps.</div>
        <div className="badge"><Link size={10} /> Webhook Ready</div>
      </div>

      <div className="card" style={{ marginBottom: '16px', border: '1px solid var(--accent-amber-glow)', background: 'rgba(245, 158, 11, 0.05)' }}>
        <div className="card-head">
          <div className="ctw">
            <div className="cicon icon-amber"><Zap size={14} /></div>
            <div className="ctitle">Global Automation Settings</div>
          </div>
        </div>
        <div className="card-body" style={{ padding: '12px' }}>
          <div style={{ display: 'flex', alignItems: 'center', justifyContent: 'space-between', marginBottom: '16px', background: 'rgba(245, 158, 11, 0.1)', padding: '12px', borderRadius: '12px', border: '1px solid var(--amber-glow)' }}>
            <div>
              <div style={{ fontSize: '14px', fontWeight: 700, color: 'var(--amber)' }}>Auto-Generate on Launch (ON/OFF)</div>
              <div style={{ fontSize: '11px', color: 'var(--text2)' }}>Automatically trigger generation when opened via automation URL or HTML file</div>
            </div>
            <label className="toggle">
              <input 
                type="checkbox" 
                checked={config.autoGenerate} 
                onChange={() => setConfig({ ...config, autoGenerate: !config.autoGenerate })} 
              />
              <div className="ttrack">
                <div className="tthumb" />
              </div>
            </label>
          </div>

          {config.autoGenerate && (
            <div style={{ background: 'rgba(245, 158, 11, 0.05)', padding: '12px', borderRadius: '12px', border: '1px solid var(--border)', marginBottom: '16px' }}>
              <div className="field" style={{ marginBottom: '12px' }}>
                <label style={{ fontSize: '11px', fontWeight: 600, display: 'block', marginBottom: '4px' }}>Auto-Generate Duration (min)</label>
                <select className="inp" value={config.autoGenerateDuration} onChange={(e) => setConfig({ ...config, autoGenerateDuration: parseInt(e.target.value) })}>
                  {[2, 5, 10, 15, 20, 25, 30].map(d => <option key={d} value={d}>{d} min</option>)}
                </select>
              </div>
              
              <div className="field" style={{ display: 'flex', alignItems: 'center', justifyContent: 'space-between', marginBottom: '12px' }}>
                <div style={{ fontSize: '11px', fontWeight: 600 }}>Auto-Download MP3</div>
                <label className="toggle">
                  <input 
                    type="checkbox" 
                    checked={config.autoDownload} 
                    onChange={() => setConfig({ ...config, autoDownload: !config.autoDownload })} 
                  />
                  <div className="ttrack"><div className="tthumb" /></div>
                </label>
              </div>

              {config.whatsappEnabled && (
                <div className="field" style={{ display: 'flex', alignItems: 'center', justifyContent: 'space-between' }}>
                  <div style={{ fontSize: '11px', fontWeight: 600 }}>Auto-Send WhatsApp Message</div>
                  <label className="toggle">
                    <input 
                      type="checkbox" 
                      checked={config.whatsappAutoSend} 
                      onChange={() => setConfig({ ...config, whatsappAutoSend: !config.whatsappAutoSend })} 
                    />
                    <div className="ttrack"><div className="tthumb" /></div>
                  </label>
                </div>
              )}
            </div>
          )}

          <div style={{ borderTop: '1px solid var(--border)', paddingTop: '16px' }}>
            <div style={{ fontSize: '11px', fontWeight: 600, textTransform: 'uppercase', color: 'var(--text-secondary)', marginBottom: '12px' }}>Enable Automation Methods</div>
            <div style={{ display: 'flex', flexWrap: 'wrap', gap: '8px' }}>
              {[
                { id: 'pwa', name: 'PWA Reminder', icon: <Bell size={12} /> },
                { id: 'macrodroid', name: 'MacroDroid', icon: <Smartphone size={12} /> },
                { id: 'webhook', name: 'Webhook/URL', icon: <Link size={12} /> },
                { id: 'shortcuts', name: 'iOS Shortcuts', icon: <Zap size={12} /> },
                { id: 'automate', name: 'Automate App', icon: <Clock size={12} /> }
              ].map(m => (
                <button 
                  key={m.id}
                  className={`btn btn-sm ${config.automationMethods.includes(m.id as any) ? 'btn-teal' : 'btn-ghost'}`}
                  style={{ fontSize: '10px', padding: '6px 10px' }}
                  onClick={() => {
                    const newMethods = config.automationMethods.includes(m.id as any) 
                      ? config.automationMethods.filter(am => am !== m.id)
                      : [...config.automationMethods, m.id as any];
                    setConfig({ ...config, automationMethods: newMethods });
                  }}
                >
                  {m.icon} {m.name}
                </button>
              ))}
            </div>
          </div>
        </div>
      </div>

      <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
        {/* PWA Section */}
        {config.automationMethods.includes('pwa') && (
          <div className="card">
            <div className="card-head" style={{ display: 'flex', alignItems: 'center', justifyContent: 'space-between' }}>
              <div className="ctw">
                <div className="cicon icon-teal"><Bell size={14} /></div>
                <div className="ctitle">PWA Daily Reminder</div>
              </div>
              <label className="toggle">
                <input 
                  type="checkbox" 
                  checked={config.pwaEnabled} 
                  onChange={() => {
                    if (!config.pwaEnabled) requestNotificationPermission();
                    setConfig({ ...config, pwaEnabled: !config.pwaEnabled });
                  }} 
                />
                <div className="ttrack">
                  <div className="tthumb" />
                </div>
              </label>
            </div>
            <div className="card-body" style={{ padding: '12px' }}>
              <div className="phi mb-4">Receive a notification to generate your podcast at a set time.</div>
              
              {config.pwaEnabled && (
                <div style={{ background: 'var(--surface2)', padding: '12px', borderRadius: '8px', marginBottom: '16px', border: '1px solid var(--border)' }}>
                  <div className="field">
                    <label style={{ fontSize: '11px', fontWeight: 600, display: 'block', marginBottom: '4px' }}>Reminder Time</label>
                    <input 
                      className="inp" 
                      type="time" 
                      value={config.pwaTime} 
                      onChange={(e) => setConfig({ ...config, pwaTime: e.target.value })} 
                    />
                  </div>
                  
                  <div className="field" style={{ marginTop: '12px' }}>
                    <label style={{ fontSize: '11px', fontWeight: 600, display: 'block', marginBottom: '4px' }}>Active Days</label>
                    <div style={{ display: 'flex', gap: '6px', marginTop: '6px' }}>
                      {['S', 'M', 'T', 'W', 'T', 'F', 'S'].map((day, i) => (
                        <button 
                          key={i}
                          className={`btn btn-sm ${config.pwaDays.includes(i) ? 'btn-teal' : 'btn-ghost'}`}
                          style={{ width: '32px', height: '32px', padding: 0, fontSize: '11px', flexShrink: 0 }}
                          onClick={() => {
                            const newDays = config.pwaDays.includes(i)
                              ? config.pwaDays.filter(d => d !== i)
                              : [...config.pwaDays, i].sort();
                            setConfig({ ...config, pwaDays: newDays });
                          }}
                        >
                          {day}
                        </button>
                      ))}
                    </div>
                  </div>
                </div>
              )}

              <div className="steps">
                <div className="step">
                  <div className="snum">1</div>
                  <div className="sdesc">Add to Home Screen from browser menu.</div>
                </div>
                <div className="step">
                  <div className="snum">2</div>
                  <div className="sdesc">Enable the toggle above and set your time.</div>
                </div>
                <div className="step">
                  <div className="snum">3</div>
                  <div className="sdesc">Tap the notification to launch and generate.</div>
                </div>
              </div>
            </div>
          </div>
        )}
        {/* MacroDroid Section */}
        {config.automationMethods.includes('macrodroid') && (
          <div className="card">
            <div className="card-head">
              <div className="ctw">
                <div className="cicon icon-blue"><Smartphone size={14} /></div>
                <div className="ctitle">MacroDroid Setup (Android)</div>
              </div>
            </div>
            <div className="card-body" style={{ padding: '12px' }}>
              <div className="phi mb-4">One-time 5-minute setup for fully automated daily briefings.</div>
              
              <div className="steps">
                <div className="step">
                  <div className="snum">1</div>
                  <div>
                    <div className="stitle">Install MacroDroid</div>
                    <div className="sdesc">Search MacroDroid on Play Store → Install → Open → Allow all permissions.</div>
                  </div>
                </div>
                <div className="step">
                  <div className="snum">2</div>
                  <div>
                    <div className="stitle">Choose Your Method</div>
                    <div className="sdesc" style={{ marginTop: '4px' }}>
                      <div style={{ marginBottom: '8px' }}>
                        <b>Option A: Local HTML File</b>
                        <button onClick={downloadAutomationHtml} className="btn btn-sm btn-ghost" style={{ marginTop: '4px', width: '100%', border: '1px solid var(--border)', fontSize: '10px' }}>
                          <Download size={12} /> Download Automation HTML
                        </button>
                      </div>
                      <div>
                        <b>Option B: Webhook URL</b>
                        <div className="code-box" style={{ marginTop: '4px', fontSize: '9px', padding: '4px', background: 'var(--surface3)', borderRadius: '4px', wordBreak: 'break-all' }}>
                          {window.location.origin}?auto=1
                        </div>
                      </div>
                    </div>
                  </div>
                </div>
                <div className="step">
                  <div className="snum">3</div>
                  <div>
                    <div className="stitle">Add Action → Launch Website</div>
                    <div className="sdesc">In MacroDroid, use "Launch Website" action and paste:</div>
                    <div className="code-box" style={{ marginTop: '4px', fontSize: '9px', padding: '4px', background: 'var(--surface3)', borderRadius: '4px' }}>
                      <div style={{ marginBottom: '4px' }}><b>HTML:</b> file:///sdcard/Download/dailypod-ai.html</div>
                      <div><b>URL:</b> {window.location.origin}?auto=1</div>
                    </div>
                  </div>
                </div>
                <div className="step">
                  <div className="snum">4</div>
                  <div>
                    <div className="stitle">🎉 Result...</div>
                    <div className="sdesc">Opens page → {config.autoGenerate ? 'Auto-generates' : 'Wait for manual tap'} → Podcast plays!</div>
                  </div>
                </div>
              </div>
            </div>
          </div>
        )}

        {/* Webhook Section */}
        {config.automationMethods.includes('webhook') && (
          <div className="card">
            <div className="card-head">
              <div className="ctw">
                <div className="cicon icon-teal"><Link size={14} /></div>
                <div className="ctitle">Webhook URL</div>
              </div>
            </div>
            <div className="card-body" style={{ padding: '12px' }}>
              <div className="phi mb-4">Use this URL in any automation app.</div>
              <div style={{ display: 'flex', gap: '6px', alignItems: 'center', background: 'var(--surface3)', borderRadius: '8px', padding: '6px 10px' }}>
                <code style={{ flex: 1, wordBreak: 'break-all', fontSize: '10px', color: '#fcd34d' }}>
                  {window.location.origin}?auto=1
                </code>
                <button className="btn-ghost btn-sm" title="Copy URL" style={{ padding: '4px' }} onClick={() => {
                  navigator.clipboard.writeText(`${window.location.origin}?auto=1`);
                  notify('Webhook URL copied!', 'success');
                }}><Copy size={12} /></button>
              </div>
            </div>
          </div>
        )}
      </div>
    </div>
  );
};
